configfile: "config/config_zika.yaml"

rule all:
    input:
        auspice_json = "auspice/zika.json",

include: "rules/usvi.smk"
include: "rules/prepare_sequences.smk"
include: "rules/construct_phylogeny.smk"
include: "rules/annotate_phylogeny.smk"
include: "rules/export.smk"

# Include custom rules defined in the config.
if "custom_rules" in config:
    for rule_file in config["custom_rules"]:

        include: rule_file

rule clean:
    """Removing directories: {params}"""
    params:
        "data ",
        "results ",
        "auspice"
    shell:
        "rm -rfv {params}"
