from snakemake.utils import min_version

# Minimum Snakemake version needed for the storage plugins used in remote_files.smk
min_version("8.0.0")

# Utility functions shared across all workflows.
include: "../shared/vendored/snakemake/config.smk"


# Use default configuration values. Extend with Snakemake's --configfile/--config options.Add commentMore actions
configfile: os.path.join(workflow.basedir, "defaults/config.yaml")

# Use custom configuration from analysis directory (i.e. working dir), if any.
if os.path.exists("config.yaml"):
    configfile: "config.yaml"


rule all:
    input:
        auspice_json = "auspice/zika.json"

include: "rules/config.smk"
include: "../shared/vendored/snakemake/remote_files.smk"
include: "rules/merge_inputs.smk"
include: "rules/prepare_sequences.smk"
include: "rules/construct_phylogeny.smk"
include: "rules/annotate_phylogeny.smk"
include: "rules/export.smk"

# Include custom rules defined in the config.
if "custom_rules" in config:
    for rule_file in config["custom_rules"]:
        # Relative custom rule paths in the config are relative to the analysisAdd commentMore actions
        # directory (i.e. the current working directory, or workdir, usually
        # given by --directory), but the "include" directive treats relative
        # paths as relative to the workflow (e.g. workflow.current_basedir).
        # Convert to an absolute path based on the analysis/current directory
        # to avoid this mismatch of expectations.
        include: os.path.join(os.getcwd(), rule_file)

rule clean:
    """Removing directories: {params}"""
    params:
        "data/metadata.tsv* ",
        "data/sequences.fasta* ",
        "data/metadata_all.tsv ",
        "data/sequences_all.fasta ",
        "results ",
        "auspice"
    shell:
        "rm -rfv {params}"
