# Sequences must be FASTA and metadata must be TSV
# Both files must be zstd compressed
sequences_url: "https://data.nextstrain.org/files/workflows/zika/sequences.fasta.zst"
metadata_url: "https://data.nextstrain.org/files/workflows/zika/metadata.tsv.zst"

# Config files
exclude: "defaults/dropped_strains.txt"
reference: "defaults/zika_reference.gb"
colors: "defaults/colors.tsv"
auspice_config: "defaults/auspice_config.json"
description: "defaults/description.md"

strain_id_field: "accession"

filter:
  group_by:
    - country
    - year
    - month
  sequences_per_group: 40
  min_date: 2012
  min_length: 5385

refine:
  coalescent: "opt"
  date_inference: "marginal"
  clock_filter_iqd: 4

ancestral:
  inference: "joint"

traits:
  columns:
    - region
    - country
  sampling_bias_correction: 3
