# Sequences must be FASTA and metadata must be TSV

# TODO XXX - remove commented lines below - only for testing the snakemake storage stuff
inputs:
  - name: ncbi
    metadata: "s3://nextstrain-data/files/workflows/zika/metadata.tsv.zst"
    sequences: "s3://nextstrain-data/files/workflows/zika/sequences.fasta.zst"
    # metadata: "https://data.nextstrain.org/files/workflows/zika/metadata.tsv.zst"
    # sequences: "https://data.nextstrain.org/files/workflows/zika/sequences.fasta.zst"

additional_inputs:
  - name: usvi
    # metadata: "data/metadata_usvi.tsv"
    # sequences: "data/sequences_usvi.fasta"
    metadata: https://raw.githubusercontent.com/nextstrain/zika/refs/heads/main/phylogenetic/data/metadata_usvi.tsv
    sequences: https://raw.githubusercontent.com/nextstrain/zika/refs/heads/main/phylogenetic/data/sequences_usvi.fasta

# Config files
exclude: "exclude.txt"
reference: "reference.gb"
colors: "colors.tsv"
auspice_config: "auspice_config.json"
description: "description.md"

strain_id_field: "accession"

filter:
  group_by:
    - country
    - year
    - month
  sequences_per_group: 40
  min_date: 2012
  min_length: 5385

refine:
  coalescent: "opt"
  date_inference: "marginal"
  clock_filter_iqd: 4

ancestral:
  inference: "joint"

traits:
  columns:
    - region
    - country
  sampling_bias_correction: 3
# 