strain_id_field: "accession"
display_strain_field: "strain"

filter:
  group_by: "country year month"
  sequences_per_group: 40
  min_date: 2012
  min_length: 5385

refine:
  coalescent: "opt"
  date_inference: "marginal"
  clock_filter_iqd: 4

ancestral:
  inference: "joint"

traits:
  columns: "region country"
  sampling_bias_correction: 3
