strain_id_field: "accession"
display_strain_field: "strain"

filter:
  min_length: 5385

subsampling: "defaults/subsampling.yaml"

refine:
  coalescent: "opt"
  date_inference: "marginal"
  clock_filter_iqd: 4

ancestral:
  inference: "joint"

traits:
  columns: "region country"
  sampling_bias_correction: 3
